//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryExtensions.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QueryExtensions.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: {
        ///        &quot;filterType&quot;: &quot;text&quot;,
        ///        &quot;type&quot;: &quot;contains&quot;,
        ///        &quot;filter&quot;: &quot;15&quot;
        ///    },
        ///    &quot;x&quot;: {
        ///        &quot;filterType&quot;: &quot;number&quot;,
        ///        &quot;type&quot;: &quot;lessThan&quot;,
        ///        &quot;filter&quot;: 1000
        ///    },
        ///    &quot;y&quot;: {
        ///        &quot;filterType&quot;: &quot;number&quot;,
        ///        &quot;operator&quot;: &quot;AND&quot;,
        ///        &quot;condition1&quot;: {
        ///            &quot;filterType&quot;: &quot;number&quot;,
        ///            &quot;type&quot;: &quot;greaterThan&quot;,
        ///            &quot;filter&quot;: 400
        ///        },
        ///        &quot;condition2&quot;: {
        ///            &quot;filterType&quot;: &quot;number&quot;,
        ///            &quot;type&quot;: &quot;les [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComplexFilter {
            get {
                return ResourceManager.GetString("ComplexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;date&quot;: {
        ///        &quot;filterType&quot;: &quot;date&quot;,
        ///        &quot;operator&quot;: &quot;OR&quot;,
        ///        &quot;condition1&quot;: {
        ///            &quot;dateFrom&quot;: &quot;2021-01-13 00:00:00&quot;,
        ///            &quot;dateTo&quot;: &quot;2021-01-15 00:00:00&quot;,
        ///            &quot;type&quot;: &quot;inRange&quot;,
        ///            &quot;filterType&quot;: &quot;date&quot;
        ///        },
        ///        &quot;condition2&quot;: {
        ///            &quot;dateFrom&quot;: &quot;2021-01-14 00:00:00&quot;,
        ///            &quot;dateTo&quot;: null,
        ///            &quot;type&quot;: &quot;equals&quot;,
        ///            &quot;filterType&quot;: &quot;date&quot;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;wellName&quot;: {
        ///        &quot;filterType&quot;: &quot;text&quot;,
        ///        &quot;type&quot;: &quot;contains&quot;,
        ///        &quot;filter&quot;: &quot;15&quot;
        ///    },
        ///    &quot;date&quot;: {
        ///        &quot;dateFrom&quot;: &quot;2021-01-12 00:00:00&quot;,
        ///        &quot;dateTo&quot;: null,
        ///        &quot;type&quot;: &quot;lessThan&quot;,
        ///        &quot;filterType&quot;: &quot;date&quot;
        ///    },
        ///    &quot;flnaDepth&quot;: {
        ///        &quot;filterType&quot;: &quot;number&quot;,
        ///        &quot;type&quot;: &quot;inRange&quot;,
        ///        &quot;filter&quot;: 0,
        ///        &quot;filterTo&quot;: 5
        ///    }
        ///}.
        /// </summary>
        internal static string DateSimpleNumberRange {
            get {
                return ResourceManager.GetString("DateSimpleNumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;targetType&quot;: {
        ///        &quot;filterType&quot;: &quot;enum&quot;,
        ///        &quot;filter&quot;: &quot;1;2&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string EnumFilter {
            get {
                return ResourceManager.GetString("EnumFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;fullName&quot;: {
        ///        &quot;filterType&quot;: &quot;text&quot;,
        ///        &quot;type&quot;: &quot;contains&quot;,
        ///        &quot;filter&quot;: &quot;jo&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string SimpleFilter {
            get {
                return ResourceManager.GetString("SimpleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;surname&quot;: {
        ///        &quot;filterType&quot;: &quot;text&quot;,
        ///        &quot;operator&quot;: &quot;OR&quot;,
        ///        &quot;condition1&quot;: {
        ///            &quot;filterType&quot;: &quot;text&quot;,
        ///            &quot;type&quot;: &quot;contains&quot;,
        ///            &quot;filter&quot;: &quot;e&quot;
        ///        },
        ///        &quot;condition2&quot;: {
        ///            &quot;filterType&quot;: &quot;text&quot;,
        ///            &quot;type&quot;: &quot;endsWith&quot;,
        ///            &quot;filter&quot;: &quot;n&quot;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string StringContainsOrEndsWith {
            get {
                return ResourceManager.GetString("StringContainsOrEndsWith", resourceCulture);
            }
        }
    }
}
